DISPLAY_WIDTH = 260
DISPLAY_HEIGHT = 190

GRAPHICS_SCALING_FACTOR = 3

ENEMY_WALKING_SPEED = 50
ENEMY_ATTACK_INITIATION_DISTANCE = 25
ENEMY_AI_IDLE_TIME_MIN = 500
ENEMY_AI_IDLE_TIME_MAX = 2000
ENEMY_AI_WALK_TIME_MIN = 100
ENEMY_AI_WALK_TIME_MAX = 500
ENEMY_MIN_TIME_BETWEEN_SPAWNING_A_GROUP = 4000
ENEMY_MAX_TIME_BETWEEN_SPAWNING_A_GROUP = 5000
ENEMY_MIN_TIME_BETWEEN_SPAWNING_ONE = 100
ENEMY_MAX_TIME_BETWEEN_SPAWNING_ONE = 200
NUMBER_OF_ENEMIES_TO_SPAWN_AT_ONCE = 10
TOTAL_NUMBER_OF_ENEMIES_TO_SPAWN = 30
MAX_NUM_OF_DEAD_ENEMIES_ON_THE_SCREEN = 50
