DISPLAY_WIDTH = 260
DISPLAY_HEIGHT = 190

GRAPHICS_SCALING_FACTOR = 3

ENEMY_WALKING_SPEED = 50
ENEMY_TO_PLAYER_MIN_DISTANCE = 35
ENEMY_AI_IDLE_TIME_MIN = 500
ENEMY_AI_IDLE_TIME_MAX = 2000
ENEMY_AI_WALK_TIME_MIN = 100
ENEMY_AI_WALK_TIME_MAX = 500
ENEMY_MIN_TIME_BETWEEN_SPAWNING = 4000
ENEMY_MAX_TIME_BETWEEN_SPAWNING = 5000
NUMBER_OF_ENEMIES_TO_SPAWN = 10
